#!/usr/bin/env python3
"""
Interactive Setup Wizard for NFL-TailSlack.
"""

import os

def prompt(question, default=""):
    resp = input(f"{question} [{default}]: ").strip()
    return resp if resp else default

def main():
    print("==================================================")
    print("        NFL-TailSlack - Setup Wizard        ")
    print("==================================================")
    print("This wizard will configure your fantasy football updates easily.\n")
    
    choice = prompt("Select platform [1) Yahoo, 2) ESPN, 3) Sleeper]", "1")
    platform = {"1": "yahoo", "2": "espn", "3": "sleeper"}.get(choice, "yahoo")
    
    team_name = prompt("Enter your exact fantasy team name", "My Team")
    frequency = prompt("Select frequency [1) quarter, 2) half, 3) full]", "2")
    freq_map = {"1": "quarter", "2": "half", "3": "full"}
    freq_str = freq_map.get(frequency, frequency if frequency in freq_map.values() else "half")
    
    webhook_url = prompt("Enter your Slack Incoming Webhook URL", "https://hooks.slack.com/services/...")
    
    yahoo_league_id = ""
    espn_league_id = ""
    espn_year = "2026"
    espn_s2 = ""
    espn_swid = ""
    sleeper_league_id = ""
    
    if platform == "yahoo":
        yahoo_league_id = prompt("Enter your Yahoo League ID (e.g. 175960)")
    elif platform == "espn":
        espn_league_id = prompt("Enter your ESPN League ID")
        espn_year = prompt("Enter season year", "2026")
        if prompt("Is your ESPN league private? (y/n)", "n").lower() == 'y':
            espn_s2 = prompt("Enter ESPN S2 cookie value")
            espn_swid = prompt("Enter ESPN SWID cookie value")
    elif platform == "sleeper":
        sleeper_league_id = prompt("Enter your Sleeper League ID")
        
    env_content = f"""# NFL-TailSlack Configuration (.env)
# Automatically generated by fantasy_setup_wizard.py

FANTASY_PLATFORM="{platform}"
FANTASY_TEAM_NAME="{team_name}"
UPDATE_FREQUENCY="{freq_str}"
SLACK_WEBHOOK_URL="{webhook_url}"

YAHOO_LEAGUE_ID="{yahoo_league_id}"
ESPN_LEAGUE_ID="{espn_league_id}"
ESPN_YEAR="{espn_year}"
ESPN_S2="{espn_s2}"
ESPN_SWID="{espn_swid}"
SLEEPER_LEAGUE_ID="{sleeper_league_id}"
"""
    
    env_path = os.path.join(os.path.dirname(__file__), ".env")
    with open(env_path, "w") as f:
        f.write(env_content)
        
    print("\n==================================================")
    print(f"Setup complete! Configuration saved to: {env_path}")
    print("You can test your notifier immediately by running:")
    print("  python3 fantasy_slack_notifier.py")
    print("==================================================")

if __name__ == "__main__":
    main()
