#!/usr/bin/env python3
"""
Interactive Setup Wizard for NFL-TailSlack.
Walks non-technical users through platform selection, team name, frequency,
league ID, and Slack webhook configuration, automatically writing a local .env file.
"""

import os

def prompt(question, default=""):
    resp = input(f"{question} [{default}]: ").strip()
    return resp if resp else default

def main():
    print("==================================================")
    print("        NFL-TailSlack - Setup Wizard        ")
    print("==================================================")
    print("This wizard will configure your fantasy football updates easily.\n")
    
    # 1. Platform selection
    print("Select your fantasy platform:")
    print("  1) Yahoo")
    print("  2) ESPN")
    print("  3) Sleeper")
    choice = prompt("Enter choice (1-3)", "1")
    platform_map = {"1": "yahoo", "2": "espn", "3": "sleeper"}
    platform = platform_map.get(choice, "yahoo")
    
    # 2. Team Name
    team_name = prompt("Enter your exact fantasy team name", "My Team")
    
    # 3. Update Frequency
    print("\nSelect update frequency:")
    print("  1) Quarter")
    print("  2) Half (Halftime)")
    print("  3) Full Game")
    freq_choice = prompt("Enter choice (1-3)", "2")
    freq_map = {"1": "quarter", "2": "half", "3": "full"}
    frequency = freq_map.get(freq_choice, "half")
    
    # 4. Slack Webhook URL
    webhook_url = prompt("Enter your Slack Incoming Webhook URL", "https://hooks.slack.com/services/...")
    
    # 5. Platform Specific IDs
    yahoo_league_id = ""
    espn_league_id = ""
    espn_year = "2026"
    espn_s2 = ""
    espn_swid = ""
    sleeper_league_id = ""
    
    if platform == "yahoo":
        yahoo_league_id = prompt("Enter your Yahoo League ID (e.g. 175960)")
    elif platform == "espn":
        espn_league_id = prompt("Enter your ESPN League ID")
        espn_year = prompt("Enter season year", "2026")
        private = prompt("Is your ESPN league private? (y/n)", "n")
        if private.lower() == 'y':
            espn_s2 = prompt("Enter ESPN S2 cookie value")
            espn_swid = prompt("Enter ESPN SWID cookie value")
    elif platform == "sleeper":
        sleeper_league_id = prompt("Enter your Sleeper League ID")
        
    # Generate .env file content
    env_content = f"""# NFL-TailSlack Configuration (.env)
# Automatically generated by fantasy_setup_wizard.py

FANTASY_PLATFORM="{platform}"
FANTASY_TEAM_NAME="{team_name}"
UPDATE_FREQUENCY="{frequency}"
SLACK_WEBHOOK_URL="{webhook_url}"

YAHOO_LEAGUE_ID="{yahoo_league_id}"
ESPN_LEAGUE_ID="{espn_league_id}"
ESPN_YEAR="{espn_year}"
ESPN_S2="{espn_s2}"
ESPN_SWID="{espn_swid}"
SLEEPER_LEAGUE_ID="{sleeper_league_id}"
"""
    
    env_path = os.path.join(os.path.dirname(__file__), ".env")
    with open(env_path, "w") as f:
        f.write(env_content)
        
    print("\n==================================================")
    print(f"Setup complete! Configuration saved to: {env_path}")
    print("You can test your notifier immediately by running:")
    print("  python3 fantasy_slack_notifier.py")
    print("==================================================")

if __name__ == "__main__":
    main()
